### ISSUE TITLE
speed limit on A/B

### ISSUE THREAD

**Issue by trackhacs** [SnakeOilXY/klipper-extended-corexy-kinematic#1]
nice - thought about that too.

since for 45° moves A/B need to have double the speed C0/C1 (with less mass though) - what max speed to you reach?

also what is your hardware setup?

**Comment by ChipCE** [comment]
The max AB speed is the same max speed as my corexy setup, about 600mm/s with the E3D high torque motor.
the hardware is https://github.com/SnakeOilXY/SnakeOil-XY

**Comment by ChipCE** [comment]
For more question, please visit our discord.

**Comment by trackhacs** [comment]
thx for the link. so many printer variants coming ;)
